 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHe19JG6cwVgrfftMeuqi-dwDTTuvzlpQ',
    appId: '1:1046646822773:web:cd3587bd62eb3acc50253c',
    messagingSenderId: '1046646822773',
    projectId: 'reddit-v2-e8f54',
    authDomain: 'reddit-v2-e8f54.firebaseapp.com',
    storageBucket: 'reddit-v2-e8f54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNX15I3kVMhmtOUbTIGzqRZjuTcX0kVOc',
    appId: '1:1046646822773:android:7fdabbf20205fcbb50253c',
    messagingSenderId: '1046646822773',
    projectId: 'reddit-v2-e8f54',
    storageBucket: 'reddit-v2-e8f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZrr5w7xB0v50xga7viF0NpCDOWWnUQU',
    appId: '1:1046646822773:ios:380d1dd9110154df50253c',
    messagingSenderId: '1046646822773',
    projectId: 'reddit-v2-e8f54',
    storageBucket: 'reddit-v2-e8f54.appspot.com',
    iosClientId: '1046646822773-hle04j0fo06u5mr2vgakohtqljdr497v.apps.googleusercontent.com',
    iosBundleId: 'com.vytautasdev.redditV2',
  );
}
